zzzeek/sqlalchemy

lib/sqlalchemy/dialects/postgresql/psycopg2.py
Hello!
I had some problems with using JSONB field in my TypeDecorator. This fixes the issue. No tests attached.
=> Psycopg2 JSONB support.

lib/sqlalchemy/orm/persistence.py, lib/sqlalchemy/orm/query.py, test/orm/test_update_delete.py
This is useful to be able to pass in mysql_limit=1 from using the
ORM.
=> Allow kwargs to be passed through update()

lib/sqlalchemy/dialects/mssql/pymssql.py
See https://github.com/pymssql/pymssql/commit/e7fb15dd29090e1f1bb570842b53aea1ec32d8f0
=> - pymssql has PEP249 Binary contructor since 2.1.1

lib/sqlalchemy/orm/relationships.py
=> Fix typo in 'Relationships API' docs

doc/build/core/metadata.rst
More readable and pep8-compatible.
=> Remove spaces around kwargs in metadata.rst

lib/sqlalchemy/engine/interfaces.py, lib/sqlalchemy/sql/compiler.py, lib/sqlalchemy/sql/schema.py, test/sql/test_defaults.py
patch to add MINVALUE to CREATE SEQUENCE / Sequence()
without this, Sequence(start=0) fails:
"sqlalchemy.exc.DataError: (DataError) START value (0) cannot be less than MINVALUE (1)"
tested with pg:
```python
#!/usr/bin/env python3.3
from sqlalchemy import Table
from sqlalchemy import Column
from sqlalchemy import SmallInteger
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import create_engine
from sqlalchemy.orm import scoped_session
from sqlalchemy.orm import sessionmaker
from sqlalchemy.orm import create_session
from sqlalchemy.schema import Sequence
DBNAME = "test_sequence_minvalue"
CONNECTION_STRING = "postgres://postgres@localhost/" + DBNAME
ENGINE = create_engine(CONNECTION_STRING, echo=False)
Session = scoped_session(sessionmaker(autocommit=False, …
```
=> add MINVALUE support to Sequence()

lib/sqlalchemy/ext/baked.py, test/ext/test_baked.py
Also add a couple of missing tests.
=> Fix sqlalchemy.ext.baked.Result.one_or_none() exception message

lib/sqlalchemy/dialects/mysql/base.py, lib/sqlalchemy/dialects/mysql/mysqlconnector.py, lib/sqlalchemy/dialects/mysql/mysqldb.py, test/dialect/mysql/test_dialect.py
Not sure if it's the right place in the API to put this. If you are ok with the approach/idea, please let me know, and I'll update the docs too.
=> Add 'native' autocommit support for mysql drivers

examples/performance/short_selects.py
Changed the docstring in short_selects example to match the code
=> Docstring Fix

doc/build/changelog/changelog_06.rst, doc/build/changelog/changelog_07.rst, lib/sqlalchemy/engine/__init__.py
=> Fix some broken links in docs

doc/build/glossary.rst
=> Doc fixes only, in glossary.rst

doc/build/orm/extensions/declarative/basic_use.rst
=> Fix documentation basic example (missing imports)

doc/build/dialects/index.rst
Next try :)
This one is much better, no changes in sqlalchemy but works as new connector.
=> pytds based connector for MS-SQL

doc/build/orm/session_api.rst
=> Fix a title typo

lib/sqlalchemy/orm/session.py
=> fixes a typo

lib/sqlalchemy/dialects/sqlite/base.py
Example http://docs.sqlalchemy.org/en/latest/dialects/sqlite.html#sqlalchemy.dialects.sqlite.TIME
=> Fix docs syntax error at sqlite3 page

doc/build/orm/tutorial.rst
The Session class was used instead of the session instance which resulted in an attribute error.
=> Replace Session class with session instance

doc/build/orm/tutorial.rst
Improve the wording of how sessions commit changes.
=> Make flush logic slightly clearer in tutorial.

lib/sqlalchemy/orm/session.py
The missing space was driving me nuts.
=> Add missing space in repr of the sessionmaker class

doc/build/orm/basic_relationships.rst
Signed-off-by: Randy Barlow <randy@electronsweatshop.com>
=> Fix a typo in basic_relationships.rst.

doc/build/core/constraints.rst
SQLite supports both of these features.
=> Remove stale ON UPDATE/ON DELETE comment.

doc/build/orm/loading_relationships.rst
The name of the strategy is `raise_on_sql` as indicated elsewhere in the documentation.
=> Fixed typo

lib/sqlalchemy/ext/hybrid.py
This PR covers the documentation updates discussed in https://groups.google.com/forum/#!topic/sqlalchemy/bm1_9GwR2fs
Specifically, this adds a warning to [the hybrid property documentation](https://docs.sqlalchemy.org/en/latest/orm/extensions/hybrid.html#defining-expression-behavior-distinct-from-attribute-behavior) that the name of the method used for a customized expression must match that of the original property/method.
I also added a link back to this section of the docs from the API documentation, and fixed a couple of broken links.
=> Add warning to hybrid property expression and fixup crosslinks

lib/sqlalchemy/event/base.py
Hi!
I've been reading through `events/base/py` and made a few
code-style tweaks and small rewrites aimed for readability - almost all
syntax-level. Most notably:
1. Simplified a bit the if-statment in `Events._accept_with`.
2. Changed attribute name from `dispatcher.dispatch_cls` to
`dispatcher.dispatch`. In this case postfix `_cls` is confusing as
the property is not a class, but an instance of one (initialised in `Events._set_dispatch`).
Cheers :)
=> Tweak code-style and readability in `events/base.py`
