lib/sqlalchemy/sql/elements.py, test/sql/test_defaults.py
This patch reports the type of unexpected expression objects, which seems to be useful in tracking down the object itself.
=> Report the type of unexpected expression objects

test/dialect/postgresql/test_types.py
This PR add a unit test to demonstrate the lack of support of UUID arrays for PostgreSQL.
This unit test produce the following error:
```bash
./sqla_nose.py --dburi=postgresql://localhost/sql_unittests test.dialect.postgresql.test_types:UUIDTest
nose.config: INFO: Set working dir to /Users/kdeldycke/virtualenvs/sqla/sqlalchemy/test
nose.config: INFO: Working directory /Users/kdeldycke/virtualenvs/sqla/sqlalchemy/test is a package; adding to sys.path
nose.config: INFO: Ignoring files matching ['^\\.', '^_', '^setup\\.py$']
nose.config: INFO: Excluding tests matching ['^examples']
test.dialect.postgresql.test_types.UUIDTest.test_no_uuid_available ... ok
test.dialect.postgresql.test_types.UUIDTest.test_uuid_array ... ERROR
test.dialect.postgresql.test_types.UUIDTest.test_uuid_string ... ok …
```
=> No support of UUID arrays for PostgreSQL.

lib/sqlalchemy/dialects/postgresql/pg8000.py, test/dialect/postgresql/test_dialect.py
Hi Mike, a couple of commits for the pg8000 dialect.
The first one makes the checking of the \__version\__ attribute cope with the version string you get in development when you use [Versioneer](https://github.com/warner/python-versioneer), as pg8000 does.
The second commit adds support for setting the client_encoding parameter from create_engine, in the same way as with psycopg2.
=> pg8000 dialect now supports client_encoding from create_engine()

lib/sqlalchemy/orm/util.py, test/orm/test_cascade.py
`cascade` should also accept unicode, instead of raising something like `ArgumentError: Invalid cascade option(s): u' ', u',', u'-', u'a', u'd', u'e', u'g', u'm', u'n', u'p', u'r', u's', u't', u'u', u'v', u'x'`
=> Accept unicode in CascadeOptions

lib/sqlalchemy/dialects/mysql/base.py
Currently, BIT fields in MySQL are broken on Python 3.
Basically, what the code is doing here is converting the value in the BIT field to a number, one byte at a time. On Python 2, the way to turn a byte into a number is `ord()`, but on Python 3, that's redundant; iterating over `bytes` already gives you numbers. Which produces the following error:
```TypeError: ord() expected string of length 1, but int found```
With a quick check of the code, I was able to find another similar issue in `lib/sqlalchemy/util/compat.py`. There may be others as well.
As an aside, do we really need to convert a bit *one byte at a time*? I suspect this code would work just as well:
```python
def process(value):
if value is None:
return None
return ord(value)  # this should work on Python 2 or 3
```
=> fix Python 2-specific byte conversion

doc/build/orm/extensions/declarative/mixins.rst, lib/sqlalchemy/sql/selectable.py
agaisnt -> against
'a Alias' -> 'an Alias'
=> Fix typos in docs

lib/sqlalchemy/util/_collections.py
This makes unique_list approx 2x faster in my (simple) tests for larg-ish sequences, and a bit faster for smaller ones.
```python
In [1]: def unique_list(seq):
...:     seen = {}
...:     return [x for x in seq
...:             if x not in seen
...:             and not seen.__setitem__(x, True)]
...: 
In [2]: def unique_list2(seq):
...:     seen = set()
...:     seen_add = seen.add
...:     return [x for x in seq
...:             if x not in seen
...:             and not seen_add(x)]
...: 
In [3]: l = list(range(10000))
In [5]: timeit unique_list(l)
100 loops, best of 3: 2.46 ms per loop
In [7]: timeit unique_list2(l)
1000 loops, best of 3: 1.1 ms per loop
In [8]: l = list(range(3))
In [9]: timeit unique_list(l)
1000000 loops, best of 3: 978 ns per loop
In [10]: timeit unique_list2(l) …
```
=> micro-optimize unique_list

lib/sqlalchemy/testing/suite/test_select.py
The sqlalchemy_exasol dialect needs to support Exasol 4.x which does not support 
the OFFSET feature. Mark test with testing.requires.offset so that they can be skipped
of in the exasol specific test suite.
=> Mark tests that they require OFFSET support in database

doc/build/orm/session_transaction.rst
Would you recommend this? For some reason, the session is not expired which can lead to weird behavior where the objects will still be in the session's identity map after the rollback/commit.
Maybe something else is wrong in how I handle tests though.
=> Expire session in testing transaction handling

lib/sqlalchemy/orm/persistence.py, test/orm/test_bulk.py
Suppose you have a model class with a primary key.
```python
Base = declarative_base()
class User(Base):
id = Column(BigInteger, primary_key=True)
name = Column(String)
```
Previously, running
`bulk_update_mappings(User, {'id': 1, 'name': 'hello'})`
would emit the following:
```sql
UPDATE users SET id=1, name='hello' WHERE id=1
```
This is contrary to the stated behaviour, where primary keys are omitted
from the SET clause. Furthermore, this behaviour is harmful, as it
can cause the db engine to lock over-aggresively (at least in Postgres).
With this change, the emitted SQL is:
```sql
UPDATE users SET name='hello' WHERE id=1
```
=> Fix primary key behaviour in bulk_update

lib/sqlalchemy/engine/result.py, lib/sqlalchemy/orm/query.py
The class comment indicates we stop growing at 100 but was going to 1000. In "yield_per" queries that return large columns (in my case huge hstore columns) the memory usage can grow larger than anticipated and means that if you need to reduce your memory requirements lower than 1000 fetched rows you can't.
=> BufferedRowResultProxy should stop growing at 100

lib/sqlalchemy/dialects/postgresql/base.py, test/dialect/postgresql/test_compiler.py, test/dialect/postgresql/test_reflection.py
Add support for specifying PostgreSQL index storage paramters (e.g.
fillfactor).
See http://www.postgresql.org/docs/9.4/static/sql-createindex.html#SQL-CREATEINDEX-STORAGE-PARAMETERS
=> Add support for PostgreSQL index storage options, and reflection of index storage options and index access methods

lib/sqlalchemy/ext/automap.py
Fix camelize_classname and pluralize_collection functions as they didn't work as expected.
=> Fix code examples in automap's documentation

lib/sqlalchemy/sql/sqltypes.py
`to_unicode` variable was created but was not used.
=> Remove useless code

setup.py
By telling wheel that we have extension modules, even though we have none, wheel will create a Wheel which is platform and interpreter specific. This will ensure that the pure Python wheels on PyPy do not trigger installs on CPython without the C speedups.
=> Tell Wheel to generate platform and interpreter specific wheels

lib/sqlalchemy/engine/__init__.py
Goes into more detail about how ``sqlalchemy.create_engine()``'s parameters are interpreted
=> engine_from_config() doc enhancement

doc/build/changelog/changelog_10.rst, doc/build/orm/tutorial.rst, lib/sqlalchemy/orm/query.py, test/orm/test_query.py
I frequently need a query executor method (is that the right term for it?) that allows 0 or 1 rows in the result -- unlike `one()`, which allows exactly 1, or `first()`, which doesn't complain about multiple rows.  I'm not the only one; see this thread from 2013: http://markmail.org/search/?q=sqlalchemy%20between%20one%20and%20first#query:sqlalchemy%20between%20one%20and%20first+page:1+mid:vz4dmlzc3ulqb2ju+state:results
`Query.opt()`, which this PR adds, does that.
N.B.: I'm not thrilled with the name -- confusingly close to the existing `Query.options()`.  If anyone can suggest a better one, I'd appreciate it.  Alternatively, the functionality could be presented as an optional argument to `one()`, e.g. `one(optional=False)` or `one(required=True)`.  I'm not fussed about the spelling; I …
=> Add Query.opt() method

lib/sqlalchemy/dialects/sqlite/base.py, test/dialect/test_sqlite.py
Add support for get_schema_names for attached databases in SQLite.
This reports the "main" database by default as well. I wasn't sure if this should actually be supported, but it's consistent with the .databases command that you can run via the CLI.
=> Support get_schema_names for SQLite dialect

lib/sqlalchemy/dialects/mssql/base.py
Docstring typo keysowrds => keywords
=> Docstring typo in base.py

doc/build/dialects/index.rst
Currently @binarydud's repo is not accepting PRs. Switch to a maintained version at https://github.com/graingert/redshift_sqlalchemy/ is
See https://github.com/graingert/redshift_sqlalchemy/issues/16
=> Link to maintained redshift dialect

lib/sqlalchemy/sql/schema.py, lib/sqlalchemy/util/__init__.py, lib/sqlalchemy/util/langhelpers.py, test/sql/test_defaults.py
Set the __name__ and __doc__ zero arg callables to those of the function it wraps.  If you introspect, you'll get some clue of what the default is.
=> wrap ColumnDefault empty arg callables like functools.wraps

lib/sqlalchemy/dialects/mssql/base.py, test/dialect/mssql/test_types.py
The simple check on the precision results in DATETIME2(0) generating a
DATETIME2 column, with default precision, which is 7.
=> Pass precision value to mssql.DATETIME2 when it is 0

lib/sqlalchemy/orm/collections.py, lib/sqlalchemy/orm/events.py, lib/sqlalchemy/testing/exclusions.py, lib/sqlalchemy/util/langhelpers.py, test/orm/test_session.py
The places inspect.getargspec was being used were causing problems for
newer Python versions.
=> Update usages of getargspec to compat version.

lib/sqlalchemy/util/__init__.py, lib/sqlalchemy/util/compat.py, test/base/test_utils.py
The error message changed to:
`'<' not supported between instances of 'foo' and 'bar'`
See https://bitbucket.org/zzzeek/sqlalchemy/pull-requests/67/
https://github.com/python/cpython/commit/9d2ff5ed5d9121982ad1057df599f1073ae65569
=> Fix _assert_unorderable_types on py36.

lib/sqlalchemy/engine/result.py, lib/sqlalchemy/ext/associationproxy.py
From [PEP 479](https://www.python.org/dev/peps/pep-0479/) the correct way to terminate a generator is to return (which implicitly raises StopIteration) rather than raise StopIteration.
Without this change using sqlalchemy in python 3.5 or greater results in these warnings
PendingDeprecationWarning: generator '__iter__' raised StopIteration
which this commit should remove.
=> Change generator termination from StopIteration to return.

doc/build/changelog/changelog_11.rst, lib/sqlalchemy/ext/declarative/clsregistry.py, test/ext/declarative/test_basic.py
Fixed bug where in Py2K a unicode literal would not be accepted as the
string name of a class or other argument within declarative using
:func:`.backref` on :func:`.relationship`.
amends commit e6f67f48054d906856f879bc1803ea639aa4b670
=> py2k: accept unicode literals on :func:`backref`, too

doc/build/core/pooling.rst
I used this example in my project and ran into an error
TypeError: 'function' object has no attribute '__getitem__'
I assume it's meant to be like line 272.
=> Fix a typo in the disconnect handling code example

lib/sqlalchemy/dialects/postgresql/ext.py, test/dialect/postgresql/test_compiler.py
currently just does `__bool__` eval, which for me causes e.g.:
```
Traceback (most recent call last):
File "/home/ai/code/sqlalchemy/test/dialect/postgresql/test_compiler.py", line 519, in test_exclude_constraint_when
cons = ExcludeConstraint(('room', '='), where=tbl.c.room.in_(['12']))
File "/home/ai/code/sqlalchemy/test/../lib/sqlalchemy/dialects/postgresql/ext.py", line 145, in __init__
if where:
File "/home/ai/code/sqlalchemy/test/../lib/sqlalchemy/sql/elements.py", line 2873, in __bool__
raise TypeError("Boolean value of this clause is not defined")
TypeError: Boolean value of this clause is not defined
```
checking `is not None`  fixed it.
=> fix postgresql exclude contraint has when= check

lib/sqlalchemy/dialects/postgresql/base.py, lib/sqlalchemy/sql/compiler.py, test/dialect/postgresql/test_compiler.py
Pull request for [Issue #3573](https://bitbucket.org/zzzeek/sqlalchemy/issues/3573)
"SqlAlchemy generates bad SQL for Postgresql SELECT...FOR UPDATE OF, because Postgresql requires the table parameter to NOT be schema qualified, but SqlAlchemy schema-qualifies the parameter anyway."
=> Postgres: Do not prefix table with schema in: "FOR UPDATE OF <table>"

doc/build/core/event.rst
Just made things a little more intuitive by reordering the parameters as mentioned in the docs to match the parameter order expected by the functions.
=> Make docs listing of param order for event.listen match the code

lib/sqlalchemy/dialects/mysql/base.py
MySQL 5.7 adds many new keywords but only four new reserved words according to https://dev.mysql.com/doc/refman/5.7/en/keywords.html#table-keywords-new-5.7
=> Add new reserved words for MySQL 5.7.

lib/sqlalchemy/dialects/postgresql/base.py
Prior to this change a value of `'{}'` would split into the list `['']`, which is doubly surprising because it was supposed to be an empty list and the value `''` isn't a valid member of the enum.
Also note this code is in a comment, it does appear to be working for me after this change though.
=> Fix ArrayOfEnum's handling of empty arrays.

doc/build/orm/tutorial.rst
Line 2046 is not displayed properly if there are double colons at the end of line 2044.
=> Fix typo in ORM tutorial doc

lib/sqlalchemy/dialects/mssql/base.py
Fixes a misrendering at http://docs.sqlalchemy.org/en/latest/dialects/mssql.html#nullability:
=> ReST fix: missing backtick

doc/build/orm/cascades.rst
There seem to be some extra words in this explanation:
> Cascade behavior is configured _using the by changing the_
=> typo: redundant "using the by changing" -> "using the"

lib/sqlalchemy/dialects/sqlite/base.py, test/dialect/test_sqlite.py, test/requirements.py
Pull request for issue [#3629 - SQLite reflection does not preserve primary key constraint names](https://bitbucket.org/zzzeek/sqlalchemy/issues/3629)
Let me know if you want it changed in any way. Thanks!
=> sqlite: reflect primary key constraint names

lib/sqlalchemy/ext/declarative/base.py
This warning confused me as it isn't clear whether something is broken or not.
I did:
class Timetable(Base):
timetable_active = Column(Boolean)
active = timetable_active
When I should have done:
class Timetable(Base):
timetable_active = Column(Boolean)
active = synonym(timetable_active)
But I'm still unsure what the consequences were of doing the former were.
=> Mention the correct way of adding multiple attributes

lib/sqlalchemy/sql/functions.py
This makes the docstring example code compatible with both Python 2 and Python 3.
=> Adds parentheses around prints in documentation

doc/build/changelog/migration_04.rst, doc/build/changelog/migration_05.rst, doc/build/changelog/migration_06.rst, doc/build/changelog/migration_07.rst, doc/build/changelog/migration_08.rst, doc/build/changelog/migration_09.rst, doc/build/changelog/migration_10.rst, doc/build/changelog/migration_11.rst, doc/build/core/connections.rst, doc/build/core/custom_types.rst, doc/build/core/event.rst, doc/build/core/metadata.rst, doc/build/core/pooling.rst, doc/build/core/reflection.rst, doc/build/core/tutorial.rst, doc/build/faq/metadata_schema.rst, doc/build/faq/performance.rst, doc/build/faq/sessions.rst, doc/build/glossary.rst, doc/build/orm/backref.rst, doc/build/orm/basic_relationships.rst, doc/build/orm/collections.rst, doc/build/orm/composites.rst, doc/build/orm/contextual.rst, doc/build/orm/extensions/declarative/mixins.rst, doc/build/orm/loading_columns.rst, doc/build/orm/mapped_attributes.rst, doc/build/orm/mapped_sql_expr.rst, doc/build/orm/session_state_management.rst, doc/build/orm/session_transaction.rst
This is a follow-up to #263. I think it catches all of the instances of print statements in the documentation.
=> Adds parentheses around print statements in docs.

doc/build/changelog/changelog_08.rst, doc/build/changelog/migration_08.rst, doc/build/changelog/migration_09.rst, doc/build/conf.py, doc/build/core/constraints.rst, doc/build/core/metadata.rst, doc/build/orm/session_basics.rst, examples/dogpile_caching/__init__.py, lib/sqlalchemy/ext/automap.py
As per their email ‘Changes to project subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified.
=> Convert readthedocs link for their .org -> .io migration for hosted projects

doc/build/dialects/index.rst
Hi, I would like to add the link to Snowflake SQLAlchemy dialect Github page.
Thanks!
=> Adding Snowflake SQLAlchemy dialect Github link to SQLAlchemy dialect index page

lib/sqlalchemy/dialects/postgresql/base.py
An example refers to both `my_table` and `tbl`, but I presume they should be referring to the same table?
=> Fix table reference in PostgreSQL documentation

lib/sqlalchemy/orm/query.py, test/orm/test_joins.py
This prevents an `IndexError` when trying to join on a query that has entities, raising a more informative error instead.
=> Provide more informative error when joining with no entities

doc/build/orm/basic_relationships.rst
This example doesn't work with 'back_populates' because 'parent_associations' and 'child_associations' are not defined in Parent and Child classes respectively.
Alternatively, we could create 'parent_associations' and 'child_associations' into the classes.
=> Corrects typo

lib/sqlalchemy/ext/declarative/api.py
The second 'if' condition was never called because the original
condition always returns.
=> Remove some legacy dead code from the declared_attr logic

lib/sqlalchemy/dialects/mysql/base.py
As title. Fixing http://docs.sqlalchemy.org/en/latest/dialects/mysql.html#charset-selection.
=> remove ambiguous line breakers to help sphinx identify code block

lib/sqlalchemy/testing/plugin/noseplugin.py
`./sqla_nose.py --dbs`  works fine with zero arguments and does not need special treatment as in pytestplugin. So `zeroarg_callback` should be treated as `callback`.
Without this change nose tests fail with:
```
$ ./sqla_nose.py
Traceback (most recent call last):
File "./sqla_nose.py", line 33, in <module>
nose.main(addplugins=[NoseSQLAlchemy()])
File "/home/ishcherb/test/sqlalchemy/venv/lib/python2.7/site-packages/nose/core.py", line 121, in __init__
**extra_args)
File "/usr/lib64/python2.7/unittest/main.py", line 94, in __init__
self.parseArgs(argv)
File "/home/ishcherb/test/sqlalchemy/venv/lib/python2.7/site-packages/nose/core.py", line 145, in parseArgs
self.config.configure(argv, doc=self.usage())
File "/home/ishcherb/test/sqlalchemy/venv/lib/python2.7/site-packages/nose/config.py", …
```
=> Fix noseplugin to accept `zeroarg_callback` for `--dbs` option

lib/sqlalchemy/engine/reflection.py
The previous example didn't have the correct `import`.
=> Fix import in Inspector.reflecttable doc

doc/build/core/custom_types.rst
Some database adapters (specifically, pg8000) already produce a uuid.UUID()
instance for UUID columns. Account for this.
Specifically, see [*AttributeError: 'UUID' object has no attribute 'replace'* on Stack Overflow](https://stackoverflow.com/q/47429929/100297), where someone using pg8000 ran into this.
=> Allow for the database to produce a UUID instance

doc/build/orm/session_state_management.rst
Micro typo fix, `True` is not our input but the output of the assert statement.
=> Fix typo in doc in python example

doc/build/core/custom_types.rst
Hi all,
I've been working on a dialect, and I stumbled upon this. This will override the original signature of the method:
https://github.com/zzzeek/sqlalchemy/blob/master/lib/sqlalchemy/sql/type_api.py#L522
Cheers, Fokko
=> Add the kwargs to the Adapt method

lib/sqlalchemy/dialects/mysql/pymysql.py
The [current link](http://www.pymysql.org/) points to a domain parking site. I've updated the URL to the official one linked from their [GitHub project](https://github.com/PyMySQL/PyMySQL).
=> Update URL for PyMySQL documentation
